name: Build

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]

jobs:
    build:
        env:
            DOTNET_CLI_TELEMETRY_OPTOUT: 0
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Build
              run: dotnet build tests/JsonmultidimensionalArrayExtesnsions.Tests/JsonmultidimensionalArrayExtesnsions.Tests.csproj --configuration Release

            - name: Test
              # run: dotnet test ./tests/JsonmultidimensionalArrayExtesnsions.Tests/JsonmultidimensionalArrayExtesnsions.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput='./../../coverage/' /p:Exclude=\"[*SampleApp*]*\"
              run: dotnet test ./tests/JsonmultidimensionalArrayExtesnsions.Tests/JsonmultidimensionalArrayExtesnsions.Tests.csproj /p:CollectCoverage=true

            # - name: Upload coverage to Codecov
            #   uses: codecov/codecov-action@v1.2.1
            #   with:
            #       token: ${{ secrets.CODECOV_TOKEN }}
            #       directory: ./coverage/
            #       flags: unittests
            #       name: codecov-umbrella
            #       fail_ci_if_error: true
            #       gcov_path_exclude: 'samples/**/*'
            #       path_to_write_report: ./coverage/codecov_report.txt
            #       verbose: true